Refactor DatatypeUnitResources Controller
opendcs/rest_api pull request #279
Opened 2024-12-19 20:24 UTC by zack-rma

## Problem Description

Fixes #224. 

## Solution

Replaces DAO usage with OpenDCS DAI implementations.

## how you tested the change

Unit tests included.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [x] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

2024-12-19 20:26 UTC, zack-rma commented
Some methods will need to be implemented in OpenDCS to complete this task

2025-01-02 20:46 UTC, rma-rripken commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java
> +					.orElseThrow(() -> new DbException(NO_UNIT_CONVERTER));
just checking - unitDao doesn't need to be closed?

2025-01-02 20:49 UTC, rma-rripken commented on opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/DatatypeUnitResourcesTest.java
> +		EngineeringUnit eu2 = new EngineeringUnit("t2", "Test2", "Test2", "Test2");
Not loving that every field has the same value.  how can you verify that you haven't crossed the streams?

2025-01-02 20:50 UTC, rma-rripken approved these changes

2025-01-02 20:51 UTC, rma-rripken requested changes
resolve the comments.

2025-01-03 00:18 UTC, zack-rma commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java
> +					.orElseThrow(() -> new DbException(NO_UNIT_CONVERTER));
Swapped for new implementation and added closure

2025-01-03 00:19 UTC, zack-rma commented on opendcs-rest-api/src/test/java/org/opendcs/odcsapi/res/DatatypeUnitResourcesTest.java
> +		EngineeringUnit eu2 = new EngineeringUnit("t2", "Test2", "Test2", "Test2");
Swapped values to improve mapping test reliability

2025-01-03 00:40 UTC, zack-rma commented
OpenDCS Toolkit changes can be found here: https://github.com/opendcs/opendcs/pull/870

Deletion bug and Toolkit support for UnitConverter deletion on XML DB in progress.

2025-01-03 00:49 UTC, rma-rripken commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java
> +			dbIo.close();
dbIo isn't Closeable or AutoCloseable such that we could use try-with-resources here - right?   If not this should probably be changed to try/finally

2025-01-03 17:07 UTC, zack-rma commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/DatatypeUnitResources.java
> +			dbIo.close();
Unfortunately, dbIo isn't Closable or AutoClosable. I've changed this and other usages to try/finally

2025-01-10 00:15 UTC, zack-rma commented
Closing due to newer PR with these changes and OpenTSDB integration testing: https://github.com/opendcs/rest_api/pull/315

2025-01-10 00:15 UTC, closed without merging