Refactored NetlistResources Controller
opendcs/rest_api pull request #282
Opened 2024-12-19 21:52 UTC by zack-rma

## Problem Description

Fixes #226. 

## Solution

Replaces DAO usage with OpenDCS implementations. 

## how you tested the change

Unit testing of data mapping included.

## Where the following done:

- [ ] Tests. Check all that apply:
   - [x] Unit tests created or modified that run during ant test.
   - [ ] Integration tests created or modified that run during integration testing
         (Formerly called regression tests.)
   - [ ] Test procedure descriptions for manual testing
- [ ] Was relevant documentation updated?
- [ ] Were relevant config element (e.g. XML data) updated as appropriate

If you aren't sure leave unchecked and we will help guide you to want needs changing where.

2024-12-19 21:54 UTC, zack-rma commented
References getAll will need a new OpenDCS DAI method to support filtering by transport medium type

2025-01-02 19:16 UTC, rma-rripken commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java
> +						.entity(" Cannot delete network list with ID " + netlistId
SC_OK  ?  seems like this should be a failure or error

2025-01-02 19:20 UTC, rma-rripken requested changes
Look at that one OK status.  The rest looks good

2025-01-03 00:51 UTC, zack-rma commented on opendcs-rest-api/src/main/java/org/opendcs/odcsapi/res/NetlistResources.java
> +						.entity(" Cannot delete network list with ID " + netlistId
Swapped for SC_CONFLICT

2025-01-03 00:54 UTC, rma-rripken approved these changes

2025-01-08 22:01 UTC, zack-rma commented
Requires Toolkit changes found here: https://github.com/adamkorynta/opendcs/pull/5

2025-01-10 00:08 UTC, closed without merging

2025-01-10 00:08 UTC, zack-rma commented
Closing due to newer PR containing integration tests and these code changes: https://github.com/opendcs/rest_api/pull/320